# -*- coding: utf-8 -*-
"""World happiness report 2023.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DbmJYMzSP6Yebc3falvtxOfsfgNSwSZf
"""

#@title Default title text

from IPython.display import HTML

html_code = """
<div style="color:white;
           display:fill;
           border-radius:2px;
           background-color:#F5DEB3;
           font-size:250%;
           font-family:Verdana;
           letter-spacing:0.5px;">
    <p style="padding: 10px;
              text-align: center;
              font-size:150%;
              color:blue;">
        🗺️ World 😊😊Happiness Report 2023📈📝
    </p>
    <style>
        h1 {
            text-align: center;
        }
    </style>
</div>
"""

HTML(html_code)

import numpy as np
import pandas as pd

df=pd.read_excel('/DataForTable2.1WHR2023.xls')

# Commented out IPython magic to ensure Python compatibility.
# %pip install dataprep

from dataprep.eda import plot, plot_correlation, plot_missing,create_db_report,create_report

world_report = create_report(df)

world_report

